name: flutter_jd
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  intl: ^0.20.2
  # 自定义下拉刷新动画.
  pull_to_refresh_notification: ^3.1.0
  # webview
  webview_flutter: ^4.2.3
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  # Flutter 的 dynamic_fonts 包允许您（相对）轻松地将动态加载的 Web 托管字体添加到您的应用程序中，就像 google_fonts 包一样，但适用于在任何地方托管的任意字体。
  dynamic_fonts: ^2.2.0
  # 在 Flutter 上原生渲染 After Effects 动画.
  lottie: ^2.6.0
  # 一个新的 Flutter 对话框，带有一系列精美的动画，滑动、淡入淡出、旋转、大小、缩放、旋转 3D 动画。
  flutter_animated_dialog_updated: ^1.0.1
  # 一个提供下拉刷新和上拉加载的flutter widget。
  easy_refresh: ^3.4.0
  # 瀑布流
  waterfall_flow: ^3.0.2
  # 强大的Sliver扩展库, 包括 SliverToNestedScrollBoxAdapter, SliverPinnedPersistentHeader,
  # SliverPinnedToBoxAdapter 和 ExtendedSliverAppbar.
  extended_sliver: ^2.1.3
  # 扩展NestedScrollView
  extended_nested_scroll_view: ^6.1.2
  # 加载更多列表支持ListView,GridView以及瀑布流。
  loading_more_list: ^6.0.0
  # 一个纯粹的flutter toast库，支持自定义样式/小部件，轻松实现与原生toast相同的效果。
  oktoast: ^3.4.0
  # 一个漂亮的flutter应用程序版本更新对话框。您可以自定义自己的版本更新弹窗！
  flutter_update_dialog: ^2.0.0
  # 一个轮播滑块小部件，支持无限滚动和自定义子部件。
  carousel_slider: ^5.1.1
  # Flutter 的地理定位插件。  该插件为通用位置（GPS 等）功能提供跨平台（iOS、Android）API。
  geolocator: ^10.0.0
  # Flutter 粘性标题和索引 ListView。  索引栏。  例如城市列表、联系人列表。  索引和悬停效果。
  azlistview:
    git:
      url: https://github.com/MiaoPaSiFlutter/azlistview.git
      ref: yh-0.3.8

  # 汉字转换拼音库。准确完整的汉字词典。转换速度快。
  lpinyin: ^2.0.3

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/home/
    - assets/images/login/
    - assets/images/news/
    - assets/images/product/
    - assets/images/store/
    - assets/images/discover/
    - assets/images/loading/
    - assets/images/guide/

    - assets/lottiefiles/
    - assets/lottiefiles/mdb_splash/
    - assets/lottiefiles/mdb_splash/images/

    - assets/azlistview/data/
    - assets/azlistview/images/

    - assets/screenshots/

    - assets/json/mock-data/functionId/@new/tab/xinpin/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getNewsTrendsTabDetails/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getRecommendNewFeedsList/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/1/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/7/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/9/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/19/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/20/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/22/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/95/
    - assets/json/mock-data/functionId/@new/tab/person/
    - assets/json/mock-data/functionId/@new/tab/person/address/
    - assets/json/mock-data/functionId/@new/tab/person/browseHistory/
    - assets/json/mock-data/functionId/@new/tab/person/favorite/
    - assets/json/mock-data/functionId/@new/tab/person/recommend/
    - assets/json/mock-data/functionId/@new/tab/person/order/
    - assets/json/mock-data/functionId/@new/tab/person/order/allOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/cancleOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/completedOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/wait4DeliveryOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/wait4PaymentOrder/
    - assets/json/mock-data/functionId/@new/tab/discFollow/
    - assets/json/mock-data/functionId/@new/tab/discFollow/discFollowNextContent/
    - assets/json/mock-data/functionId/@new/tab/discovery/
    - assets/json/mock-data/functionId/@new/tab/discovery/follow/
    - assets/json/mock-data/functionId/@new/tab/discovery/feedStream/
    - assets/json/mock-data/functionId/@new/tab/category/
    - assets/json/mock-data/functionId/@new/tab/category/cid/
    - assets/json/mock-data/functionId/@new/tab/category/cid/0/
    - assets/json/mock-data/functionId/@new/tab/category/cid/300014703/
    - assets/json/mock-data/functionId/@new/tab/category/cid/300015294/
    - assets/json/mock-data/functionId/@new/tab/category/cid/300015359/
    - assets/json/mock-data/functionId/@new/tab/cart/
    - assets/json/mock-data/functionId/@new/tab/cart/confirmOrder/
    - assets/json/mock-data/functionId/@new/tab/cart/uniformRecommend/
    - assets/json/mock-data/functionId/@new/tab/home/
    - assets/json/mock-data/functionId/@new/tab/home/hours/
    - assets/json/mock-data/functionId/@new/tab/home/category/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/234/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/237/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/246/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/248/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/700/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/1761/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/2230/
    - assets/json/mock-data/functionId/@new/tab/home/category/pmid/
    - assets/json/mock-data/functionId/@new/tab/home/category/pmid/142/
    - assets/json/mock-data/functionId/@new/product/
    - assets/json/mock-data/functionId/@new/product/shopId/
    - assets/json/mock-data/functionId/@new/product/shopId/19769/
    - assets/json/mock-data/functionId/@new/product/shopId/19769/sku/
    - assets/json/mock-data/functionId/@new/product/shopId/19769/sku/44096580396/
