name: game_the_green_ninja
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/audio/effects/
    - assets/images/
    - assets/images/effects/
    - assets/images/items/
    - assets/images/sprite_sheets/
    - assets/images/decorations/
