name: flutter_projects
publish_to: none
environment:
  sdk: ^3.8.0

dev_dependencies:
  melos: ^7.0.0-dev.9

workspace:
  - packages/athena_common
  - packages/athena_components
  - packages/athena_constants
  - packages/athena_core
  - packages/athena_utils
  - packages/athena_network
  - packages/hzy_normal_tool
  - packages/hzy_normal_network
  - packages/hzy_common_module

  - packages_game/game_the_green_ninja
  - packages_game/game_math_app

  - packages_test/extended_sliver_demo
  - packages_test/scrollerview_demo
  - packages_test/animation_demo
  - packages_test/canvas_demo
  - packages_test/common_demo

  - packages_ui/ui_coffe_app
  - packages_ui/ui_food_app
  - packages_ui/ui_tesla_app
  - packages_ui/ui_blogclub_app
  - packages_ui/ui_facebook_app
  - packages_ui/ui_fd_daily_task_app
  - packages_ui/ui_fd_project_management_app
  - packages_ui/ui_foodybite_app
  - packages_ui/ui_instagram_app
  - packages_ui/ui_motion_animations_reply_app
  - packages_ui/ui_pay_now_ewallet_app
  - packages_ui/ui_smart_home_app
  - packages_ui/ui_animated_rive_app
  - packages_ui/ui_animated_travel_app
  - packages_ui/ui_chat_message_app
  - packages_ui/ui_clock_app
  - packages_ui/ui_goplan_app
  - packages_ui/ui_online_shopping_app
  - packages_ui/ui_parallax_effect_app
  - packages_ui/ui_smart_home_animated_app
  - packages_ui/ui_task_management_app
  - packages_ui/ui_ticket_booking_app
  - packages_ui/ui_ecommerce_complate_app
  - packages_ui/ui_ecommerce_mobile_app
  - packages_ui/ui_responsive_app
  - packages_ui/ui_shoe_app
  - projects/athena_common_flutter
  - projects/athena_app
  - projects/flutter_demo

melos:
  # All of the content of your previous melos.yaml file
  # (Except for the packages and name)
  scripts:
    hello:
      name: hey
      description: Greet the world
      run: echo '$GREETING World'
      env:
        GREETING: "Hey"

      analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

    pub_get:
      run: melos exec --flutter "flutter pub get"
      description: pub get

    build_all:
      run: melos exec --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
      description: build_runner build all modules

    format:
      run: melos exec -- "flutter format . --set-exit-if-changed"
      description: Run `flutter format .` in all packages

    test:
      run: melos exec --dir-exists=test -- "flutter test"
      description: Run `flutter test` in all packages

    runalone_bootstrap_athena_app:
      run: melos exec --scope="projects/athena_app" -- 'flutter pub get'
      description: 为 athena_app 单独执行 pub get
