name: flutter_oorbswallpaper_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  flutter_localizations:
    sdk: flutter
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  json_path: ^0.7.6
  # json_path:
  #   git:
  #     url: https://github.com/f3ath/jessie.git
  # Flutter 小部件可自动调整文本大小以完美适合其边界。
  auto_size_text: ^3.0.0
  # 用于加载和缓存网络图像的 Flutter 库。  还可以与占位符和错误小部件一起使用。
  cached_network_image: ^3.4.1
  # 用于将国家/地区代码转换为表情符号标志的 dart 库。
  emoji_flag_converter: ^1.1.0
  # 一个 Dart 包，有助于实现基于值的相等，而无需显式覆盖 == 和 hashCode。
  equatable: ^2.0.5
  # 一个简单但完全可定制的 flutter 评级栏，其中还包括一个评级栏指示器，支持任何评级部分。
  flutter_rating_bar: ^4.0.1
  # 带有颤动动画的加载指示器的集合。  深受 @tobiasahlin 的 SpinKit 启发。
  flutter_spinkit: ^5.2.0
  # Font Awesome 图标包可作为 Flutter 图标使用。  提供 1600 个附加图标以在您的应用程序中使用。
  font_awesome_flutter: ^10.5.0
  # 使用 fonts.google.com 字体的 Flutter 包。  支持 HTTP 获取、缓存和资源捆绑。
  google_fonts: ^5.1.0
  # 将网络或临时文件中的图像和视频保存到外部存储。  图像和视频都将在 Android 图库和 iOS 照片中可见。
  # gallery_saver: 2.3.2
  # 适用于 Google 移动广告的 Flutter 插件，支持横幅广告、插页式广告（全屏）、激励广告和原生广告
  # google_mobile_ads: 3.0.0
  # google_mobile_ads:
  #   git:
  #     url: https://github.com/asmengistu/googleads-mobile-flutter
  #     ref: b943dffb925bf7a527a981d12d34a5797c34a37d
  #     path: packages/google_mobile_ads/
  # 包含处理国际化/本地化消息、日期和数字格式和解析、双向文本以及其他国际化问题的代码。
  intl: ^0.20.2
  # JSONPath 表达式的实现，例如“$.store.book[2].price”。  读取和写入解析的 JSON 对象中的值。
  # json_path: 0.6.5
  # 在 Flutter 上原生渲染 After Effects 动画。  这个包是 Lottie 播放器的纯 Dart 实现。
  lottie: ^2.6.0
  # Flutter Page Transition Package 也就是过渡第二个页面
  page_transition: ^2.1.0
  # 照片视图提供了手势敏感的可缩放小部件。  照片视图主要用于显示交互式图像和其他内容，例如 SVG。
  photo_view: ^0.14.0
  # 可定制的动画页面指示器，具有一组内置效果。
  smooth_page_indicator: ^1.1.0
  # 用于创建模糊时间戳的库。  （例如“15 分钟前”）
  timeago: ^3.7.1
  # 功能丰富的跨平台 Web 视图，在移动设备上使用 webview_flutter，在 Web 上使用 iframe。  JS 互操作就绪。
  # webviewx: 0.2.1

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
