name: ui_ticket_booking_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.1
dependencies:
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  fluentui_icons: 1.0.0
  gap: 3.0.1
  barcode_widget: 2.0.4

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
