name: hzy_normal_tool
description: 项目开发基础工具
version: 0.0.3
homepage: "https://gitee.com/tengteng_fan/hzy_normal_tool.git"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
