name: common_demo
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  # 通用
  ocean_common_module:
    path: ../../packages/ocean_common_module
  # 一个 Flutter 插件，用于为提供的小部件实现液体滑动效果。
  liquid_swipe: ^3.1.0
  # 抖动动画、向上弹出动画、抖动文本、垂直圆形菜单、底部圆形菜单、动画进度按钮
  shake_animation_widget: ^3.0.4
  # 用于轻松创建 Matrix4 转换的辅助数学类，您可以在容器的转换参数和其他地方使用它。
  matrix4_transform: ^2.0.1
  # 该包包含预制动画，可实现常见的所需效果
  animations: ^2.0.8

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/
