name: ui_smart_home_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.1
dependencies:
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  google_fonts: 5.1.0
  flutter_svg: 2.0.8
  eva_icons_flutter: 3.1.0
  persistent_bottom_nav_bar_v2: 6.1.0
  fl_chart: 0.63.0
  another_xlider: 3.0.1
  animated_toggle_switch: 0.8.0

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/img/
    - assets/svg/
