# arb-dir: lib/flutter_black_hole/l10n
# template-arb-file: app_en.arb
# output-localization-file: app_localizations.dart

# Options used by the localizations tool
## `arb-dir` sets the input directory. The output directory will match
## the input directory if the output directory is not set.
arb-dir: lib/flutter_black_hole/l10n
## `header-file` is the file that contains a custom
## header for each of the generated files.
header-file: header.txt
## `output-class` is the name of the localizations class your
## Flutter application will use. The file will need to be
## imported throughout your application.
output-class: AppLocalizations
## `output-localization-file` is the name of the generated file.
output-localization-file: app_localizations.dart
## `template-arb-file` describes the template arb file that the tool
## will use to check and validate the remaining arb files when
## generating Flutter's localization files.
synthetic-package: false
template-arb-file: app_en.arb
## setting `nullable-getter` to false generates a non-nullable
## StockStrings getter. This removes the need for adding null checks
## in the Flutter application itself.
nullable-getter: false
## Run the formatter on the generated localization files.
format: true
##
untranslated-messages-file: untranslated_messages.json
