name: flutter_black_hole
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
    # 用于读取 ID3 标签并将其写入 MP3 文件的库。  您可以获取 Map 对象或 Tag 对象的数据。
  audiotagger:
    path: ../../packages/audiotagger
    
  cached_network_image: ^3.4.1
  # 适用于 Flutter 的 Android 应用程序链接、深层链接、iOs 通用链接和自定义 URL 方案处理程序（包括桌面版）。
  app_links: ^3.4.5
  # Flutter 插件可在屏幕关闭时在后台播放音频。
  audio_service: ^0.18.12
  # 一个轮播滑块小部件，支持无限滚动和自定义子部件。
  carousel_slider: ^5.1.1
  # Flutter 插件用于发现 Android 和 iOS 上的网络（WiFi 和移动/蜂窝）连接状态。
  connectivity_plus: ^5.0.1
  # 该算法是 DES 和 Triple DES 算法的纯 dart 实现。
  dart_des: ^1.0.2
  # Flutter 插件提供有关设备（品牌、型号等）以及应用程序运行的 Android 或 iOS 版本的详细信息。
  device_info_plus: ^9.1.0
  # 一个包，允许您使用本机文件资源管理器来选择单个或多个绝对文件路径，并支持扩展名过滤。
  file_picker: ^10.2.0
  # 提供翻转卡片动画的组件。  它可用于隐藏和显示产品的详细信息。
  flip_card: ^0.7.0
  # Create and extract ZIP archive files in Android, iOS and macOS. Zip all files in a directory recursively or a given list of files.
  flutter_archive: ^5.0.0
  # 一款音乐歌词阅读器，支持高亮、翻译歌词、流畅动画、自定义 UI 和解析。
  flutter_lyric: ^2.0.4+6
  # 简单的直接服务定位器，允许将接口与具体实现解耦，并从应用程序中的任何位置访问具体实现”
  get_it: ^7.6.4
  # 用纯 Dart 编写的轻量级且速度极快的键值数据库。  使用 AES-256 进行严格加密。
  hive: ^2.2.3
  # Hive 的扩展。  使在 Flutter 应用程序中使用 Hive 变得更加容易。
  hive_flutter: ^1.1.0
  # 一个插件，提供用于创建 Android 和 iOS 主屏幕小部件的通用界面。
  # home_widget: ^0.3.0
  # 一个用于取消转义 HTML 的小型库。  支持所有命名字符引用、十进制字符引用和十六进制字符引用。
  html_unescape: ^2.0.0
  # 功能丰富的 Flutter 音频播放器。  以各种音频格式循环、剪辑和连接来自任何来源（资产/文件/URL/流）的任何声音，并进行无缝播放。
  just_audio: ^0.9.35
  # Discontinued, Use just_audio_windows instead.
  # just_audio_libwinmedia: ^0.0.4 # For windows and linux.
  # 提供用于调试和错误日志记录的API，类似于其他语言中的记录器，例如Closure JS Logger和java.util.logging.Logger。
  logging: ^1.2.0
  # 一个可以无限滚动文本的 Flutter 小部件。  提供许多自定义功能，包括自定义滚动方向、持续时间、曲线以及每轮后的暂停。
  marquee: ^2.3.0
  # 社区为 Flutter 设计的 Material Design 图标
  material_design_icons_flutter: ^7.0.7296
  # 用于从音频文件检索和写入音频标签/元数据的插件
  # metadata_god: 1.0.0
  # Flutter 插件用于从设备存储查询音频/歌曲信息 [标题、艺术家、专辑等]。
  on_audio_query: ^2.9.0
  # Flutter 包用于从源图像生成调色板颜色。
  palette_generator: ^0.3.3+3
  # Flutter 的持久/静态底部导航栏。
  persistent_bottom_nav_bar:
    path: ../../packages/persistent_bottom_nav_bar

  # 一个 flutter 插件，使 flutter 应用程序能够接收来自其他应用程序的共享照片、文本或 url。
  # receive_sharing_intent: 1.4.5
  # Flutter 插件用于通过平台共享 UI 共享内容，在 Android 上使用 ACTION_SEND 意图，在 iOS 上使用 UIActivityViewController。
  share_plus: ^7.2.1
  # 一个 Flutter 插件，可轻松使 Flutter 应用程序响应。  自动调整 UI 以适应不同的屏幕尺寸。  响应能力变得简单。
  sizer: ^2.0.15
  # 一个可拖动的 Flutter 小部件，使实现 SlidingUpPanel 变得更加容易！
  sliding_up_panel: ^2.0.0+1

  # 颤振工作管理器。  该插件允许您在 Android 和 iOS 上安排后台工作。
  workmanager: ^0.5.1
  # youtube 爆炸库的 dart 中的端口。  支持多种API函数，无需Youtube API Key。
  youtube_explode_dart: ^2.0.2
  # A Flutter plugin to set display mode (resolution, refresh rate) on Android platform.
  # Allows to enable high refresh rate on supported devices.
  flutter_displaymode: ^0.6.0

  # 国际化
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
