name: flutter_chat_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  # 通用
  ocean_common_module:
    path: ../../packages/ocean_common_module
  chat:
    path: ./chat
  # 一个可预测的状态管理库，有助于实现 BLoC（业务逻辑组件）设计模式。
  bloc: ^8.1.2
  # Flutter Widgets 可以轻松实现 BLoC（业务逻辑组件）设计模式。  专为与块状态管理包一起使用而构建。
  flutter_bloc: ^8.1.3
  # 一个 Dart 包，有助于实现基于值的相等，而无需显式覆盖 == 和 hashCode。
  equatable: ^2.0.5
  # 创建令人惊叹且强大的模态底部表单。  Material、Cupertino iOS 13 或创建您自己的风格
  modal_bottom_sheet: ^3.0.0-pre

  google_fonts: ^5.1.0
  http: ^1.3.0
  image_picker: ^1.0.0
  intl: ^0.20.2
  path: ^1.9.1
  # 这是一个在 Dart 和 Flutter 中使用 RethinkDB 支持 Null Safety 的非官方驱动程序，
  # 该驱动程序基于一个分支 https://github.com/marceloneppel/rethinkdb
  rethink_db_ns: ^0.0.4
  shared_preferences: ^2.2.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
