name: flutter_weather
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  #
  animation_search_bar: ^0.0.10
  intl: ^0.20.2
  gradient_borders: ^1.0.0
  weather_animation: ^0.0.2
  location: ^5.0.3
  lottie: ^2.6.0
  cupertino_listview: ^2.0.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.1.1
  sleek_circular_slider: ^2.0.1
  smooth_compass: ^2.0.4
  arrow_path: ^3.0.0
  weather_icons: ^3.0.0
  # Flutter 包用于从源图像生成调色板颜色。
  palette_generator: ^0.3.3+3

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/animations/
