package_rename_config:
  android:
    app_name: S
    package_name: rocks.outdatedguy.packagerenamedemo

  ios:
    app_name: S
    bundle_name: renamedemo
    package_name: rocks.outdatedguy.packagerenamedemo

  web:
    app_name: S
    description: Package to change project configurations.

  linux:
    app_name: S
    package_name: rocks.outdatedguy.packagerenamedemo
    exe_name: renamedemo-linux-x64

  windows:
    app_name: S
    organization: OutdatedGuy
    copyright_notice: Copyright ©️ 2022 OutdatedGuy. All rights reserved.
    exe_name: renamedemo-win32

  macos:
    app_name: S
    package_name: rocks.outdatedguy.packagerenamedemo
    copyright_notice: Copyright ©️ 2022 OutdatedGuy. All rights reserved.
