name: example_normal
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  # web 模拟器
  device_frame: ^1.1.0
  # 支持markdown
  flutter_markdown: ^0.6.14
  string_scanner: ^1.2.0
  flutter_screenutil: ^5.9.3
  # 一个软件包，可简化更新 Flutter 应用程序启动器图标的任务。
  flutter_launcher_icons: ^0.13.1
  # 修改包名。
  package_rename: ^1.3.3
  get: ^4.6.5

  camera: ^0.10.6

  json_path: ^0.7.6

  ####### packages
  hzy_common_module:
    path: ../../packages/hzy_common_module
  audiotagger:
    path: ../../packages/audiotagger
  persistent_bottom_nav_bar:
    path: ../../packages/persistent_bottom_nav_bar

  ### 游戏
  game_the_green_ninja:
    path: ../../packages_game/game_the_green_ninja
  game_math_app:
    path: ../../packages_game/game_math_app

  ####### ui
  ui_coffe_app:
    path: ../../packages_ui/ui_coffe_app
  ui_food_app:
    path: ../../packages_ui/ui_food_app
  ui_tesla_app:
    path: ../../packages_ui/ui_tesla_app
  ui_blogclub_app:
    path: ../../packages_ui/ui_blogclub_app
  ui_facebook_app:
    path: ../../packages_ui/ui_facebook_app
  ui_fd_daily_task_app:
    path: ../../packages_ui/ui_fd_daily_task_app
  ui_fd_project_management_app:
    path: ../../packages_ui/ui_fd_project_management_app
  ui_foodybite_app:
    path: ../../packages_ui/ui_foodybite_app
  ui_instagram_app:
    path: ../../packages_ui/ui_instagram_app
  ui_motion_animations_reply_app:
    path: ../../packages_ui/ui_motion_animations_reply_app
  ui_pay_now_ewallet_app:
    path: ../../packages_ui/ui_pay_now_ewallet_app
  ui_smart_home_app:
    path: ../../packages_ui/ui_smart_home_app
  ui_animated_rive_app:
    path: ../../packages_ui/ui_animated_rive_app
  ui_animated_travel_app:
    path: ../../packages_ui/ui_animated_travel_app
  ui_chat_message_app:
    path: ../../packages_ui/ui_chat_message_app
  ui_clock_app:
    path: ../../packages_ui/ui_clock_app
  ui_goplan_app:
    path: ../../packages_ui/ui_goplan_app
  ui_online_shopping_app:
    path: ../../packages_ui/ui_online_shopping_app
  ui_parallax_effect_app:
    path: ../../packages_ui/ui_parallax_effect_app
  ui_smart_home_animated_app:
    path: ../../packages_ui/ui_smart_home_animated_app
  ui_task_management_app:
    path: ../../packages_ui/ui_task_management_app
  ui_ticket_booking_app:
    path: ../../packages_ui/ui_ticket_booking_app
  ui_ecommerce_complate_app:
    path: ../../packages_ui/ui_ecommerce_complate_app
  ui_ecommerce_mobile_app:
    path: ../../packages_ui/ui_ecommerce_mobile_app
  ui_responsive_app:
    path: ../../packages_ui/ui_responsive_app
  ui_shoe_app:
    path: ../../packages_ui/ui_shoe_app

  ####### app
  flutter_chat_app:
    path: ../../packages_app/flutter_chat_app
  flutter_jd:
    path: ../../packages_app/flutter_jd
  flutter_books:
    path: ../../packages_app/flutter_books
  flutter_weather:
    path: ../../packages_app/flutter_weather
  flutter_black_hole:
    path: ../../packages_app/flutter_black_hole
  flutter_muet_attendance_taking_app:
    path: ../../packages_app/flutter_muet_attendance_taking_app
  flutter_foodhub_app:
    path: ../../packages_app/flutter_foodhub_app
  flutter_paytabs_tickets_app:
    path: ../../packages_app/flutter_paytabs_tickets_app
  flutter_oorbswallpaper_app:
    path: ../../packages_app/flutter_oorbswallpaper_app
  flutter_nimbus_app:
    path: ../../packages_app/flutter_nimbus_app
  flutter_fitness_app:
    path: ../../packages_app/flutter_fitness_app
  flutter_periodic_table_app:
    path: ../../packages_app/flutter_periodic_table_app
  flutter_to_do_app:
    path: ../../packages_app/flutter_to_do_app
  flutter_marketky_app:
    path: ../../packages_app/flutter_marketky_app
  flutter_crypto_market_app:
    path: ../../packages_app/flutter_crypto_market_app
  flutter_chatgpt_app:
    path: ../../packages_app/flutter_chatgpt_app
  flutter_valorant_app:
    path: ../../packages_app/flutter_valorant_app
  flutter_compass_app:
    path: ../../packages_app/flutter_compass_app
  flutter_quiz_app:
    path: ../../packages_app/flutter_quiz_app
  ##### test
  extended_sliver_demo:
    path: ../../packages_test/extended_sliver_demo
  scrollerview_demo:
    path: ../../packages_test/scrollerview_demo
  animation_demo:
    path: ../../packages_test/animation_demo
  canvas_demo:
    path: ../../packages_test/canvas_demo
  common_demo:
    path: ../../packages_test/common_demo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tabbar/
    - assets/images/my/
    - assets/images/example/
    - assets/markdown/
