name: flutter_foodhub_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.0
dependencies:
  # 通用
  hzy_common_module:
    path: ../../packages/hzy_common_module
  # 一个高度可定制、功能强大且易于使用的 Flutter 警报库。
  flash: ^3.0.5+1
  # Flutter plugin for SQLite, a self-contained, high-reliability, embedded, SQL database engine.
  sqflite: ^2.4.2
  # RxDart 是流行的reactiveX api 的实现，用于异步编程，利用本机Dart Streams api。
  rxdart: ^0.27.7
  # 包含处理国际化/本地化消息、日期和数字格式和解析、双向文本以及其他国际化问题的代码。
  intl: ^0.20.2
  # 用于检查小部件的 Flutter 包。  对于快速调试或 QA 测试很有用。
  inspector: ^2.1.0
  # 通过 Inspection，您可以像 Laravel 框架一样验证 Flutter 和 Dart 中的输入。
  inspection:
    git:
      url: https://github.com/radensaleh/inspection.git
      ref: master

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  fonts:
    - family: sofia
      fonts:
        - asset: assets/fonts/sofiapro-light.otf
