name: ui_task_management_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.1
dependencies:
  # 通用
  ocean_common_module:
    path: ../../packages/ocean_common_module

  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.8
  sizer: ^2.0.15
  intl: ^0.20.2

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
    - assets/svg/
