name: ui_goplan_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
resolution: workspace
environment:
  sdk: ^3.8.1
dependencies:
  # 通用
  ocean_common_module:
    path: ../../packages/ocean_common_module

  font_awesome_flutter: ^10.5.0
  otp_text_field: ^1.1.3

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
    - assets/lib/
